/**
 * Client-side PDF export for track lyrics using jsPDF.
 * Runs entirely in the browser — no backend endpoint needed.
 */

import type { Track } from "./api";

// Lazy-load jsPDF to avoid SSR issues (it references `window`)
async function getJsPDF() {
  const { jsPDF } = await import("jspdf");
  return jsPDF;
}

/** Parse structured lyrics into segments with optional section tags */
function parseLyrics(raw: string): { tag: string | null; lines: string[] }[] {
  const segments: { tag: string | null; lines: string[] }[] = [];
  let currentTag: string | null = null;
  let currentLines: string[] = [];

  for (const line of raw.split("\n")) {
    const tagMatch = line.match(/^\[(.+?)\]$/);
    if (tagMatch) {
      if (currentLines.length > 0 || currentTag !== null) {
        segments.push({ tag: currentTag, lines: currentLines });
      }
      currentTag = tagMatch[1];
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }
  if (currentLines.length > 0 || currentTag !== null) {
    segments.push({ tag: currentTag, lines: currentLines });
  }
  return segments;
}

/** Wrap long text lines to fit a given max pixel width */
function wrapText(doc: InstanceType<Awaited<ReturnType<typeof getJsPDF>>>, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

export async function downloadLyricsPdf(track: Track): Promise<void> {
  const JsPDF = await getJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 20;
  const contentWidth = pageWidth - marginX * 2;

  let y = 20;

  const addPage = () => {
    doc.addPage();
    y = 20;
    drawFooter();
  };

  const checkY = (needed: number) => {
    if (y + needed > pageHeight - 18) addPage();
  };

  const drawFooter = () => {
    const pageCount = (doc.internal as any).getNumberOfPages?.() ?? 1;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by SargamAI", marginX, pageHeight - 10);
    doc.text(
      `Page ${pageCount}`,
      pageWidth - marginX,
      pageHeight - 10,
      { align: "right" },
    );
  };

  // ── Gradient header bar ───────────────────────────────────────────────
  doc.setFillColor(32, 178, 170); // teal
  doc.rect(0, 0, pageWidth, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("SargamAI  ·  Lyrics Export", marginX, 9.5);

  y = 22;

  // ── Title ─────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(30, 30, 30);
  const titleLines = wrapText(doc, track.title, contentWidth);
  checkY(titleLines.length * 9 + 4);
  doc.text(titleLines, marginX, y);
  y += titleLines.length * 9 + 2;

  // ── Meta chips (genre · language · date) ─────────────────────────────
  const date = new Date(track.created_at).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  const meta = [track.genre, track.language, date].filter(Boolean).join("  ·  ");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(meta, marginX, y);
  y += 5;

  // ── Divider ───────────────────────────────────────────────────────────
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.4);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 7;

  // ── Copyright badge ───────────────────────────────────────────────────
  if (track.copyright_safe !== null && track.copyright_safe !== undefined) {
    checkY(8);
    const safe = track.copyright_safe;
    doc.setFillColor(safe ? 220 : 255, safe ? 252 : 237, safe ? 231 : 213);
    doc.roundedRect(marginX, y - 4, 38, 6, 1, 1, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(safe ? 21 : 180, safe ? 128 : 83, safe ? 61 : 9);
    doc.text(safe ? "✓  Copyright Safe" : "⚠  Copyright Review", marginX + 2, y);
    y += 9;
  }

  // ── Lyrics ────────────────────────────────────────────────────────────
  if (track.generated_lyrics) {
    const segments = parseLyrics(track.generated_lyrics);

    for (const seg of segments) {
      // Section tag heading
      if (seg.tag) {
        checkY(10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(32, 178, 170);
        doc.text(`[ ${seg.tag} ]`, marginX, y);
        y += 6;
      }

      // Lyric lines
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(40, 40, 40);

      for (const line of seg.lines) {
        const wrapped = wrapText(doc, line === "" ? " " : line, contentWidth);
        for (const wline of wrapped) {
          checkY(6);
          doc.text(wline, marginX, y);
          y += 5.5;
        }
      }
      y += 3; // spacing between segments
    }
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.setTextColor(160, 160, 160);
    doc.text("No lyrics available.", marginX, y);
    y += 8;
  }

  // ── Final footer on last page ─────────────────────────────────────────
  drawFooter();

  doc.save(`${track.title.replace(/[^a-z0-9]/gi, "_")}_lyrics.pdf`);
}
